[package]
name = "diskhasher"
author = "Hyohko"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
#clap = { version = "3.2.16", features = ["derive"] }
clap = { version = "4.0.15", features = ["derive"] }
digest = "0.10"
filesize = "0.2.0"
hex = "0.4.3"
md5 = "0.7"
regex = "1"
sha1 = "0.10"
sha2 = "0.10"
threadpool = "1.8.1"
walkdir = "2"