[package]
name = "diskhasher"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
#clap = { version = "3.2.16", features = ["derive"] }
clap = { version = "4.0.15", features = ["derive"] }
walkdir = "2"
filesize = "0.2.0"
regex = "1"
digest = "0.10"
# md5 = "0.7"
sha1 = "0.10"
sha2 = "0.10"
hex = "0.4.3"